### ISSUE TITLE
Step 2 test e2e clarification

### ISSUE THREAD

**Issue by cnishina** [angular/angular-phonecat#298]
> If our controller is available on the global namespace then we could simply instantiate it with a mock scope object:

> test/e2e/scenarios.js:

Following the guide on step 2, the sample code could be improved. I followed the steps and added the sample code to `test/e2e/scenarios.js`. I tried it out and I was not able to get it to work.

The statement "if our controller is available on the global namespace" might need clarification...either there should be a protractor example here that works or there should be steps to show the user how to add the controller to the global namespace.

**Comment by JeanPerriault** [comment]
Yes I agree, this is not very clear what needs to be done here.
Here is the result/error I see with the mock implementation in e2e tests (scenario.js):
```
Failures:
  1) PhoneListCtrl should create "phones" model with 3 phones
   Message:
     ReferenceError: PhoneListCtrl is not defined
```

then with the $controller (Testing non-Global Controllers) also added in e2e tests (scenario.js):
```
Failures:
  1) PhoneListCtrl encountered a declaration exception
   Message:
     TypeError: module is not a function
```

It is not clear why we jump from e2e tests to unit tests.

Note that with unit tests in "controllersSpec.js", it is working well (at least with the "$controller code")
