### ISSUE TITLE
Step 12: Animations in phone-detail Glitchy

### ISSUE THREAD

**Issue by arjunmehta** [angular/angular-phonecat#96]
Here are some steps you can take to fix the animation glitches on the phone detail.

First: the border-bottom on the H1 {{phone.name}} binding shows in the small space between the images as they are being slid up. This doesn't look nice :-1:

Fix it by:
a) removing border-bottom from h1 in app.css

``` css
h1 {
  /*border-bottom: 1px solid gray;*/
}
```

or b) make the background of the phone-images block white in app.css

``` css
.phone-images {
  background-color: white; /*new */
  width: 450px;
  height: 450px;
  overflow: hidden;
  position: relative;
  float: left;
}
```

Second: Phone images are visible under each other and revealed as ghosts as the images scroll up/down. This more or less goes away once the user has cycled through all images.

To fix: Either make all but the first image opacity:0 on load, or make them all positioned outside of the container except for the first. ie: in app.css

``` css
img.phone {
  float: left;
  margin-right: 3em;
  margin-bottom: 2em;
  background-color: white;
  padding: 2em;
  height: 400px;
  width: 400px;
  position: absolute; /*new */
  top: 500px; /*new */
}

img.phone:first-child {
  top: 0;
}
```

Notice the position: absolute there.
